# Generated by Django 5.1.5 on 2025-01-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
