# Generated by Django 5.1.5 on 2025-02-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_notificate_student_notificate_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificate',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notification', to='school.teacher'),
        ),
    ]
