# Generated by Django 5.1.5 on 2025-02-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_notificate_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificate',
            name='sender',
        ),
    ]
