# Generated by Django 5.1.5 on 2025-02-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
